### ISSUE TITLE
使用绝对路径启动logobproxy不成功

### ISSUE THREAD

**Issue by ziyoo0830** [oceanbase/oblogproxy#13]
#1 使用绝对路径启动：
[root@52ff51c2a702 conf]# /usr/local/oblogproxy/run.sh start
work path : /usr/local/oblogproxy
is_running : (6815)/usr/local/oblogproxy logproxy is running !
Terminated

#1 使用相对路径启动：
[root@52ff51c2a702 oblogproxy]# cd /usr/local/oblogproxy/
[root@52ff51c2a702 oblogproxy]# ls
bin  conf  run.sh
[root@52ff51c2a702 oblogproxy]# bash ./run.sh start
work path : /usr/local/oblogproxy
logproxy started!

**Comment by fankux** [comment]
OK, It would be solved soon.

**Comment by fankux** [comment]
It has been fixed: #15
