### ISSUE TITLE
配置ob用户密码后校验失败

### ISSUE THREAD

**Issue by zhaozizhou** [oceanbase/oblogproxy#31]
配置oblogproxy中ob_sys用户密码后报错如下
com.oceanbase.clogproxy.client.exception.LogProxyClientException: LogProxy refused handshake request: code: 502
message: "Failed to auth"

![324632b1ca320267f9e5a5b97aa0836](https://user-images.githubusercontent.com/54111592/170484863-a2407068-a67e-4331-b218-9ccde47310bd.png)

**Comment by whhe** [comment]
在修复版本发布前，可以把配置文件中的 auth_user 置为 false 来暂时规避

**Comment by staryzhou** [comment]
我也是碰到同样的问题。但配置auth_user后，又出现了其它的问题。连接后可正常创建通道。但后面又报通道已存在。
logproxy.INFO日志如下：(已开启debug,trace)

`Log file created at: 2022/06/10 03:53:47
Running on machine: rde-confluence
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
I20220610 03:53:47.421953 25817 channel.cpp:311] ChannelFactory init with server mode
I20220610 03:53:47.423369 25817 communicator.cpp:120] +++ Listen on port: 2983, fd: 7
I20220610 03:53:47.423382 25817 communicator.cpp:126] +++ Communicator about to start
I20220610 03:54:27.315358 25817 communicator.cpp:81] On connect from '10.20.115.2:65123, fd: 8
I20220610 03:54:27.315434 25817 channel.cpp:463] create a plain channel of peer: 8
I20220610 03:54:27.315519 25817 communicator.cpp:212] Add channel, peer: file_desc:8,
I20220610 03:54:27.315554 25817 communicator.cpp:225] +++ Add read channel to Communicator with peer: file_desc:8,
I20220610 03:54:27.405848 25817 communicator.cpp:422] On event fd: 8 got channel, peer: file_desc:8,
I20220610 03:54:27.406031 25817 msg_buf.cpp:117] got EOF while call next
I20220610 03:54:27.406141 25817 arranger.cpp:53] Arranger on_msg fired: file_desc:8,
I20220610 03:54:27.406185 25817 arranger.cpp:56] Handshake request from peer: file_desc:8, , msg: log_type:0, id:10.20.115.2_23168_1654847667, ip:10.20.115.2, version:1.0.1, configuration:tb_white_list=sys.test.* cluster_user=root rootse
rver_list=10.20.210.63:2882:2881 first_start_timestamp=0 cluster_password=E625ECB5B157DED97F0956E287F586A5A25A913A , enable_monitor:0,
I20220610 03:54:27.406364 25817 arranger.cpp:112] Client connecting: type:0, id:10.20.115.2_23168_1654847667, ip:10.20.115.2, version:1.0.1, configuration:tb_white_list=sys.test.* cluster_user=root rootserver_list=10.20.210.63:2882:2881
first_start_timestamp=0 cluster_password=E625ECB5B157DED97F0956E287F586A5A25A913A , peer:fd:8, register_time:1654847667, enable_monitor:0, packet_version:2,
W20220610 03:54:27.406404 25817 communicator.cpp:492] >>> Fork preparing, fetching lock...
W20220610 03:54:27.406774 25817 communicator.cpp:494] --- Fork prepared, fetched lock
I20220610 03:54:27.407459 25817 thread.cpp:41] << Joining thread: ForkThread(25820)
I20220610 03:54:27.407524 25827 thread.cpp:58] +++ Create thread: ForkThread(25820)
I20220610 03:54:27.410583 25827 source_invoke.cpp:102] +++ create oblogreader with pid: 25828
I20220610 03:54:27.411442 25829 thread.cpp:58] +++ Create thread: WaiterThread for pid:25828(25821)
I20220610 03:54:27.411569 25817 thread.cpp:43] >> Joined thread: ForkThread(25820)
W20220610 03:54:27.411617 25817 communicator.cpp:499] <<< Fork after, unlock
I20220610 03:54:27.411700 25817 communicator.cpp:231] --- Removed channel from Communicator which steal: 0, peer: file_desc:8,  flag:2
I20220610 03:54:27.411726 25817 arranger.cpp:144] Client connected: 10.20.115.2_23168_1654847667
I20220610 03:54:27.411753 25817 channel.cpp:49] delete Channel
I20220610 03:54:29.322353 25817 communicator.cpp:81] On connect from '10.20.115.2:65125, fd: 8
I20220610 03:54:29.322413 25817 channel.cpp:463] create a plain channel of peer: 8
I20220610 03:54:29.322453 25817 communicator.cpp:212] Add channel, peer: file_desc:8,
I20220610 03:54:29.322484 25817 communicator.cpp:225] +++ Add read channel to Communicator with peer: file_desc:8,
I20220610 03:54:29.322551 25817 communicator.cpp:422] On event fd: 8 got channel, peer: file_desc:8,
I20220610 03:54:29.322598 25817 msg_buf.cpp:117] got EOF while call next
I20220610 03:54:29.322631 25817 arranger.cpp:53] Arranger on_msg fired: file_desc:8,
I20220610 03:54:29.322657 25817 arranger.cpp:56] Handshake request from peer: file_desc:8, , msg: log_type:0, id:10.20.115.2_23168_1654847667, ip:10.20.115.2, version:1.0.1, configuration:tb_white_list=sys.test.* cluster_user=root rootse
rver_list=10.20.210.63:2882:2881 first_start_timestamp=0 cluster_password=E625ECB5B157DED97F0956E287F586A5A25A913A , enable_monitor:0,
I20220610 03:54:29.322785 25817 arranger.cpp:112] Client connecting: type:0, id:10.20.115.2_23168_1654847667, ip:10.20.115.2, version:1.0.1, configuration:tb_white_list=sys.test.* cluster_user=root rootserver_list=10.20.210.63:2882:2881
first_start_timestamp=0 cluster_password=E625ECB5B157DED97F0956E287F586A5A25A913A , peer:fd:8, register_time:1654847669, enable_monitor:0, packet_version:2,
W20220610 03:54:29.322815 25817 arranger.cpp:122] duplication exist clientId and channel
E20220610 03:54:34.121160 25829 source_invoke.cpp:172] oblogreader exit failed:0`


logproxy.WARNING报如下：
`Log file created at: 2022/06/10 03:54:27
Running on machine: rde-confluence
Running duration (h:mm:ss): 0:00:39
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
W20220610 03:54:27.406404 25817 communicator.cpp:492] >>> Fork preparing, fetching lock...
W20220610 03:54:27.406774 25817 communicator.cpp:494] --- Fork prepared, fetched lock
W20220610 03:54:27.411617 25817 communicator.cpp:499] <<< Fork after, unlock
W20220610 03:54:29.322815 25817 arranger.cpp:122] duplication exist clientId and channel
E20220610 03:54:34.121160 25829 source_invoke.cpp:172] oblogreader exit failed:0`

**Comment by fankux** [comment]
fixed: #34
