### ISSUE TITLE
logproxy需要支持自动关闭过期连接

### ISSUE THREAD

**Issue by KaimingWan** [oceanbase/oblogproxy#32]
需求描述：logproxy client可能会由于一些外部不可知的原因（例如机器突发crash、用户强制kill -9）等导致client被异常关闭，没有显式向server发起close请求，这种时候需要logproxy server支持识别这种过期、无效的connection

**Comment by namewxt1220** [comment]
This issue has been fixed, and version 2.0.0 and above is recommended.
