### ISSUE TITLE
compile failed.

### ISSUE THREAD

**Issue by zetatez** [oceanbase/oblogproxy#4]
[root@server01 buildenv]# find ~ -name liboblog.so
/root/ob/oceanbase/build_debug/src/liboblog/src/liboblog.so
[root@server01 buildenv]# CMAKE_INCLUDE_PATH=/root/ob/oceanbase/build_debug/src/liboblog/src/liboblog.so CMAKE_LIBRARY_PATH=/root/ob/oceanbase/build_debug/src/liboblog/src/liboblog.so cmake ..
-- DEP_VAR:
-- JAVA_HOME:
-- C compiler: /usr/bin/gcc
-- C++ compiler: /usr/bin/g++
-- AR compiler: /usr/bin/gcc-ar
NUM_OF_PROCESSOR:16
-- ssl:/usr/lib64/libssl.so
-- crypto:/usr/lib64/libcrypto.so
gflag:/root/ob/oblogproxy/buildenv/third-party/install/gflags/include,/root/ob/oblogproxy/buildenv/third-party/install/gflags/lib/libgflags.a
-- Protobuf protoc executable: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/bin/protoc
-- Protobuf-lite library: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.6.0
protoc: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/bin/protoc, proto inc: , lib: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/lib/libprotobuf.a, /root/ob/oblogproxy/buildenv/third-party/install/protobuf/lib/libprotoc.a, protos: /root/ob/oblogproxy/proto/logproxy.proto
proto:/root/ob/oblogproxy/proto/logproxy.proto
protoc: /root/ob/oblogproxy/buildenv/third-party/install/protobuf/bin/protoc, proto srcs : /root/ob/oblogproxy/buildenv/proto/logproxy.pb.cc
CMake Error at CMakeLists.txt:144 (message):
  Fail to find liboblog

-- Configuring incomplete, errors occurred!
See also "/root/ob/oblogproxy/buildenv/CMakeFiles/CMakeOutput.log".
See also "/root/ob/oblogproxy/buildenv/CMakeFiles/CMakeError.log".

**Comment by fankux** [comment]
"CMAKE_INCLUDE_PATH" and "CMAKE_LIBRARY_PATH" is the "directory" instead of 'file', so just set both CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH to '/root/ob/oceanbase/build_debug/src/liboblog/src/' is ok,  and make sure "liboblog.h" be in there also.

**Comment by zetatez** [comment]
Thanks for your help. By now, cmake passed, but I can not downlowd dep repos from github. Is there any pre-compiled version of oblogproxy ?
