### ISSUE TITLE
[Bug]: oblogproxy always reports No such channel. fd =10

### ISSUE THREAD

**Issue by fddmgg77** [oceanbase/oblogproxy#41]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
oblogproxy 1.0.1
```

### Fast Reproduce Steps

After oblogproxy is deployed according to the documentation on the official website, the java client keeps reconnecting when connecting to the Java client

### Actual Behavior

Check oblogproxy background always find always in
![image](https://user-images.githubusercontent.com/118799231/203461942-3298e6d7-50bb-4c1a-b5b5-525d62b9685f.png)

**Comment by fddmgg77** [comment]
oblogproxy is not compatible with the new dependency package

**Comment by longdafeng** [comment]
This bug has been fixed, please refer to https://ask.oceanbase.com/t/topic/20400583
