### ISSUE TITLE
oblogproxy有arm版吗？没有的话，能尽快支持吗？

### ISSUE THREAD

**Issue by yunf17** [oceanbase/oblogproxy#45]
oblogproxy有arm版吗？没有的话，能尽快支持吗？ 万分感谢！！！

**Comment by whhe** [comment]
代码是支持的，程序包会在近期放出，从下一个版本开始和x86一起发布。

**Comment by yunf17** [comment]
> 代码是支持的，程序包会在近期放出，从下一个版本开始和x86一起发布。

您好，我看1.1.2发版了，目前有ARM版了吗？
