### ISSUE TITLE
> 代码是支持的，程序包会在近期放出，从下一个版本开始和x86一起发布。

### ISSUE THREAD

**Issue by yunf17** [oceanbase/oblogproxy#48]
> 代码是支持的，程序包会在近期放出，从下一个版本开始和x86一起发布。

您好，我看1.1.2发版了，目前有ARM版了吗？

_Originally posted by @yunf17 in https://github.com/oceanbase/oblogproxy/issues/45#issuecomment-1659648853_

**Comment by whhe** [comment]
抱歉回复的这么晚，arm 支持和 libobcdc 4.2 的适配一起带进了 oblogproxy 1.1.3，目前在走发版流程，预计下周会同步出来。

**Comment by whhe** [comment]
1.1.3已发布，可以在GitHub Releases页面或者官网下载中心下载了。
