### ISSUE TITLE
[Bug]: the latest oblogproxy(1.1.3) doesn't support OB 4.1.x CE

### ISSUE THREAD

**Issue by xiaodp** [oceanbase/oblogproxy#49]
### Describe the bug

the latest release doc says that "The packages with prefix oblogproxy-ce-for-4x-1.1.3 can be used with OceanBase [v4.2.0_CE_BETA](https://github.com/oceanbase/oceanbase/releases/tag/v4.2.0_CE_BETA) and early 4.x versions."

and I download this one: https://github.com/oceanbase/oblogproxy/releases/download/v1.1.3/oblogproxy-ce-for-4x-1.1.3-20230815201457.tar.gz

when trying with the demo code LogProxyClientTest.java, the oblogproxy report
```
E20231023 19:15:40.825059 2986164 mysql_protocol.cpp:239] Failed to query observer:Table 'oceanbase.__all_virtual_server_clog_stat' doesn't exist, unexpected column count: 0
```
the OB version : 5.7.25-OceanBase_CE-v4.1.0.1
select version() -- 5.7.25-OceanBase_CE-v4.1.0.1

### Environment

OS : 3.10.0-1160.92.1.el7.x86_64 

OB: 5.7.25-OceanBase_CE-v4.1.0.1

oblogproxy: oblogproxy-ce-for-4x-1.1.3-20230815201457.tar.gz

### Fast reproduce steps

it's simple to reproduce

**Comment by whhe** [comment]
The status check failure does not affect to fetch clog data from observer, and the logic will be removed in the future releases.
