### ISSUE TITLE
[Enhancement]: Show detailed message for 'failed to create oblogreader' error

### ISSUE THREAD

**Issue by whhe** [oceanbase/oblogproxy#51]
### Description

For now (up to 2.0.0), if the process failed to create oblogreader, the error message does not contain the root cause for it, and it's hard to figure out how to fix the issue from the client side. Hope it could show the detailed message in the error response.

**Comment by namewxt1220** [comment]
Yes, this needs to return details, I plan to release a bp version to fix it.
