### ISSUE TITLE
[Question]: oblogproxy什么时候出支持OB 4.2.2的版本呢？

### ISSUE THREAD

**Issue by winwill2012** [oceanbase/oblogproxy#54]
### Description

看现在最新的oblogproxy仅仅支持ob 4.2.1的版本
<img width="856" alt="image" src="https://github.com/oceanbase/oblogproxy/assets/9719716/dd474999-18f7-4951-9c43-282a1f33158a">
请问一下，有没有对应的计划，什么时候出支持OB V4.2.2版本的proxy呢？

**Comment by namewxt1220** [comment]
已发布新版，新版本支持 ob v4.2.2.x，请查看[releases](https://github.com/oceanbase/oblogproxy/releases/tag/v2.0.1_BP1)，或者访问[官网](https://open.oceanbase.com)获取详细信息。
