### ISSUE TITLE
No cluster IP related information is specified when oblogproxy is started may lead to problems.

### ISSUE THREAD

**Issue by zetatez** [oceanbase/oblogproxy#7]
Question: According to the README file, there was no cluster IP related information is specified when the oblogproxy is started. When there are multiple clusters in the same network segment and the clusters share the same user name and password, it will lead to misunderstanding.

**Comment by whhe** [comment]
As far as I know, `username`, `password` and `rsList` are only used when oblogclient connects to oblogproxy, so they don't need to be concerned when starting the service.

**Comment by zetatez** [comment]
I mean the communication between the oblogproxy and the observers, not the oblogclient to the oblogproxy.

Does the oblogproxy connect to the observer according to the `rsList`, `username` and `password` passed by the oblogclient?

**Comment by whhe** [comment]
> Does the oblogproxy connect to the observer according to the `rsList`, `username` and `password` passed by the oblogclient?

Yes, so oblogproxy can fetch log from different observer clusters according to the requests of multiple oblogclient instances.

**Comment by zetatez** [comment]
Thanks! One more question, In oblogclient, can we set multiple observers to `rsList`?  
```java
ObReaderConfig config = new ObReaderConfig();
// set root server list in format [ip:rpc_port:sql_port]
config.setRsList("127.0.0.1:2882:2881");
```

**Comment by fankux** [comment]
> Thanks! One more question, In oblogclient, can we set multiple observers to `rsList`?
> 
> ```java
> ObReaderConfig config = new ObReaderConfig();
> // set root server list in format [ip:rpc_port:sql_port]
> config.setRsList("127.0.0.1:2882:2881");
> ```

seperated by ';' 
`ip1:rpc_port1:sql_port1;ip2:rpc_port2:sql_port2`

These ip-ports must be the same ob cluster.

**Comment by zetatez** [comment]
Thanks !
